@startuml
namespace DotNeet {
	namespace DotNeet.Providers {
	namespace DotNeet.Providers.ComickFun {
		class Page {
		}
		class Chapter {
			+ title : string <<get>> <<set>>
			+ id : string <<get>> <<set>>
			+ chap : string <<get>> <<set>>
			+ md_images: List<TPage> <<get>> <<set>>
		}
		class Manga {
			+ title : string <<get>> <<set>>
			+ slug : string <<get>> <<set>>
			+ id : string <<get>> <<set>>
			+ desc : string <<get>> <<set>>
			+ last_chapter : string <<get>> <<set>>
		}
		Provider o-- Manga
		Provider o-- Chapter
		Provider o-- Page
		class Provider {
			+ Provider()
			+ <<const>> Alias : string = "battwo"
			+ <<override>> <<async>> GetMangaList(query:string) : Task<List<Manga>>
			+ <<override>> <<async>> GetManga(mangaIndex:int, mangaList:List<Manga>) : Task<Manga>
			+ <<override>> <<async>> GetChapter(chapIndex:int, chapterList:List<Chapter>, search:bool) : Task<Chapter>
			+ <<override>> <<async>> GetPages(chap:Chapter) : Task<List<Page>>
			+ <<override>> <<async>> GetPage(url:string) : Task<dynamic>
			+ <<override>> GetChapterUrl(manga:Manga, chap:Chapter) : String
		}
	}
	}
	BasePage <|-- DotNeet.Providers.Battwo.Page
	"BaseChapter`1" "<Page>" <|-- DotNeet.Providers.Battwo.Chapter
	"BaseManga`1" "<Chapter>" <|-- DotNeet.Providers.Battwo.Manga
	"MangaProvider`3" "<Manga,Chapter,Page>" <|-- DotNeet.Providers.Battwo.Provider
}
@enduml
