@startuml
namespace DotNeet {
	namespace DotNeet.Providers {
		class ProvidersList {
			+ {static} GetProviderList <<get>> : string[]
			+ {static} GetProvider(name:string) : dynamic
		}
	}
}
@enduml
